/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DragAndDropContainer {
        "containerTitle": string;
        "group": string;
    }
    interface DraggableItem {
        "assigneeAvatar": string;
        "dueDate": string;
        "taskTitle": string;
    }
}
declare global {
    interface HTMLDragAndDropContainerElement extends Components.DragAndDropContainer, HTMLStencilElement {
    }
    var HTMLDragAndDropContainerElement: {
        prototype: HTMLDragAndDropContainerElement;
        new (): HTMLDragAndDropContainerElement;
    };
    interface HTMLDraggableItemElement extends Components.DraggableItem, HTMLStencilElement {
    }
    var HTMLDraggableItemElement: {
        prototype: HTMLDraggableItemElement;
        new (): HTMLDraggableItemElement;
    };
    interface HTMLElementTagNameMap {
        "drag-and-drop-container": HTMLDragAndDropContainerElement;
        "draggable-item": HTMLDraggableItemElement;
    }
}
declare namespace LocalJSX {
    interface DragAndDropContainer {
        "containerTitle"?: string;
        "group"?: string;
    }
    interface DraggableItem {
        "assigneeAvatar"?: string;
        "dueDate"?: string;
        "taskTitle"?: string;
    }
    interface IntrinsicElements {
        "drag-and-drop-container": DragAndDropContainer;
        "draggable-item": DraggableItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "drag-and-drop-container": LocalJSX.DragAndDropContainer & JSXBase.HTMLAttributes<HTMLDragAndDropContainerElement>;
            "draggable-item": LocalJSX.DraggableItem & JSXBase.HTMLAttributes<HTMLDraggableItemElement>;
        }
    }
}
